title: <p align='center'> Joseph Azanza </p> # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align='left'>
  Joseph Matthew R. Azanza
  <br><br>
  Data Scientist with training in Molecular Biology, Biotechnology, Sales Operations, Marketing Operations, Business Intelligence, and Strategic Initiatives
  <br><br>
  MS Data Science Candidate (Asian Institute of Management) <br>
  BS Molecular Biology and Biotechnology (University of the Philippines Diliman)
  </p>
  
  <p align='center'>
  <a href="https://www.linkedin.com/in/josephazanza/">Reach out via LinkedIn</a>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
